### ISSUE TITLE
INSPIRE and Guidlines for RDF encoding

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#1]
http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/

Read this! Very relevant for our NEN3610 linked data project. The doc specifies detailed encoding rules from XML encoding based on UML models to several RDF formats

'This document specifies an additional encoding rule supporting the consistent representation of spatial data sets that meet the interoperability requirements using RDF. It builds on previous work on this subject. All issues are raised and discussed in an open forum: 
[https://github.com/inspire-eu-rdf/inspire-rdf-guidelines](url)'

**Comment by pvgenuchten** [comment]
also relevant is this document, which is one of the research documents behind the above mentioned guideline https://ies-svn.jrc.ec.europa.eu/attachments/download/1188/ARE3NA-RDF_vocabulary_guidelines_Final.pdf

**Comment by architolk** [comment]
We hebben deze guidelines nu opgenomen (sectie 4.2) en gerelateerd aan onze transformatie. Kan daarmee dit issue worden gesloten? Mogelijk dat de link van pvgenuchten nog meegenomen moet worden in 4.2?

**Comment by PalmJanssen** [comment]
link is toegevoegd
