### ISSUE TITLE
Par. 6.2 is nog te technisch en moeilijk te doorgronden

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/NEN3610-Linkeddata#20]
De tekst van [paragraaf 6.2 - Meta-Object-Facility][1] moet herschreven worden zodat deze begrijpelijker wordt. 

[1]: https://geonovum.github.io/NEN3610-Linkeddata/#Meta-Object-Facility

**Comment by architolk** [comment]
Tekst is verplaatst naar hoofdstuk 9 en vereenvoudigd.
