### ISSUE TITLE
definitieve keuze maken voor RDF vocabulaires voor beschrijven model

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/NEN3610-Linkeddata#21]
[Paragraaf 7.2.1][1] beschrijft 

> basisregels en uitwerking van details voor transformatie van UML constructen naar LD (RDF) encoding. 

> Voor de transformatie van een UML model naar Linked Data maken we gebruik van de volgende vocabulaires:
> RDF
> RDFS
> OWL
> SKOS
> SHACL

De keuze voor deze vocabulaires is voorlopig. Het is van belang om deze keuze zo goed mogelijk te verantwoorden. De keuze voor RDF en OWL ligt voor de hand, maar de keuze van SHACL verdient wat meer aandacht.

[1]: https://geonovum.github.io/NEN3610-Linkeddata/#Transformatie:%20basisregels%20-%20encoding

**Comment by architolk** [comment]
Ik heb de tekst enigszins aangepast, aangezien een keuze tussen SHACL en OWL niet goed te maken is. Er zitten zowel aan SHACL als aan OWL voor- en nadelen. Ik heb nu geprobeerd om aan te geven wat het verschil is, en dat we in de vertaling "simpelweg" beide aanbieden, om daarbij aan te geven wat je daarmee uitdrukt, en aan de modelleur over laat of hij het UML meer wil interpreteren "op z'n SHACL's" (dus als beperkende gegevensregels), of "op z'n OWL's" (dus als afleidende proposities). Of beide... of een beetje van beide..

**Comment by architolk** [comment]
Gesloten conform voorstel.
