### ISSUE TITLE
modellering NEN3610 id

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/NEN3610-Linkeddata#22]
We hebben nog niet besloten hoe we een NEN3610ID gaan modelleren.

**Comment by PalmJanssen** [comment]
Wordt uitgewerkt:
Voorstel: wordt op dezelfde manier als NEN 3610 vertaald naar een class NEN3610Id met tevens een werkbare LD implementatie.
1) id eigenschappen als aparte gegevens (soort metadata) van de set aan gegevens toevoegen
2) een LD implementatie waarmee de relaties gerealiseerd kunnen worden.
