### ISSUE TITLE
SHACL anders positioneren (discussie)

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#25]
Discussie over het SHACL model als meta meta model. SHACL is ook relevant voor COINS en OROX, alleen niet bij het conceptuele onderdeel maar wel als het om data (validatie) gaat.

De vraag is daarom of SHACL een plaats heeft op het conceptuele niveau.

Wordt nog uitgezocht.

**Comment by architolk** [comment]
SHACL is nu gepositioneerd als het metametamodel voor het afleiden van een model uit data (of een metametamodel uit een metamodel). Daarmee zeggen we hier niets meer dan dat we een transformator hebben gemaakt die een SHACL model maakt, met als reden dat dit een W3c standaard is.
