### ISSUE TITLE
Discussie over UNA

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#26]
1. Wat is UNA? Unique Name Assumption
2. UML adopteerd UNA
3. OWL doet dat niet automatisch

Uitleg en consequentie opnemen.

**Comment by lvdbrink** [comment]
UNA betekent volgens mij de aanname dat een ding maar één naam (id) heeft. Dus verschillende namen verwijzen naar verschillende dingen (in de werkelijkheid). 

OWL gaat hier NIET van uit, dus hier kunnen verschillende namen verwijzen naar hetzelfde ding in de werkelijkheid. Daarom bestaan owl:sameAs en owl:differentFrom ook: om aan te geven dat twee namen verwijzen naar hetzelfde ding, of juist dat ze dat niet doen. 

De consequentie is volgens mij dat dit bijdraagt aan het open world principe. Je kan zo nl op verschillende URIs triples over een subject publiceren. Een subject naam = een URI. Verschillende instanties kunnen op eigen URIs informatie over hetzelfde ding publiceren. 

Is dit zo goed uitgelegd? We kunnen deze of soortgelijke uitleg toevoegen aan https://geonovum.github.io/NEN3610-Linkeddata/#basisprincipes-identificatie.

Iets uitgebreidere uitleg staat hier: https://www.w3.org/TR/sdw-bp/#globally-unique-ids

**Comment by lvdbrink** [comment]
Het is relevant in relatie tot 
1) kardinaliteit: Doordat OWL geen UNA heeft werken cardinaliteiten niet in OWL zoals in UML. Voorbeeld huwelijk: relatie tussen 2 personen. Als je dan in instanties hebt staan dat persoon x met y is getrouwd en ook persoon x met z is getrouwd, is dat in UML fout en in OWL leid je af dat y = z. 
2) In UML heb je UNA, maar in de praktijk komt het voor dat in verschillende datasets voor hetzelfde obj in de werkelijkheid verschillende id's hebben. Daar heeft UML geen oplossing voor, OWL wel.

**Comment by NielsHoffmann** [comment]
Volgens mij staat dit nu duidelijk beschreven in 5.2
