### ISSUE TITLE
Gebruik bij uitleg transformatie regels IMGolf voorbeelden

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#27]
Gebruik bij voorbaat IMGolf voorbeelden. Dan wordt het een meer integrale tekst.
Dan moet IMGolf wel voldoende materiaal bieden voor gebruik voorbeelden.

IMGolf moet daarom mogelijk aangepast worden.

**Comment by lvdbrink** [comment]
Bijna overal wordt nu wel IMGolf gebruikt.
