### ISSUE TITLE
Overweging - Use case XML uitwisseling is vaak anders dan LD ontsluiting

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#3]
De use case van XML berichtenverkeer is meestal om gecontroleerde data-uitwisseling te realiseren in ketenuitwisselingstrajecten. Bijvoorbeeld van bronhouder naar centrale voorziening, of tussen centrale voorzieningen. Kenmerkend voor deze uitwisseltrajecten is dat de gestandaardiseerde omgeving zorgt voor  interoperabiliteit op technische en semantisch niveau inclusief validatie. Logisch dat een conceptueel model in UML het construct multipliciteit van attributen en relaties kent.

Linked data publicatie zit vaak aan de front end van de datadistributie, de informatie-ontsluiting. Hier worden andere eisen gesteld aan semantisch detail. Wat dat betreft is het logisch dat RDF geen multipliciteit van attributen of relaties kent.

Het hangt van de toepassing van je LD model af het wenselijk is dat multipliciteit meegenomen moet worden in de UML-LD transformatie. Dit kan per use case verschillen.

**Comment by architolk** [comment]
Is dit nog relevant? Multipliciteit is op zichzelf best belangrijk en wordt in de modellen ook meegenomen (zie ook onze transformatie). Voorstel: deze issue sluiten?
