### ISSUE TITLE
Uitleg normalisatie niveau's

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/NEN3610-Linkeddata#34]
De [paragraaf over normalisatie][1] kan duidelijker. De verschillende niveau's van normalisatie worden nu niet expliciet uitgelegd. Het zou helpen als we hier iets meer over zeggen, zonder dat we te diep in de theorie van relationele databases duiken. Een afbeelding kan hierbij denk ik goed helpen, die de verschillende niveau's afbeeldt met een aanduiding welke de werkelijkheid het dichtst benadert. 

[1]: https://geonovum.github.io/NEN3610-Linkeddata/#basisprincipes-normalisatie

**Comment by MarinusVonhof** [comment]
Eens met Hans (mail 20181002): normaliseren is wel echt een relationeel-database-ding, het RDF/Linked data principe conflicteert zelfs? Misschien niet te diep op in gaan, maar alleen de relevantie voor de transformatie vanuit het "genormaliseerde" UML benoemen.

**Comment by architolk** [comment]
@MarinusVonhof : is de nieuwe tekst wat jou betreft nu akkoord? (inclusief het stuk over classificatie). Zo ja, dan kan dit issue mogelijk worden afgesloten?

**Comment by MarinusVonhof** [comment]
Prima Marco. Bedankt voor de toevoegingen, afsluiten maar.

**Comment by architolk** [comment]
Closed
