### ISSUE TITLE
Overweging - SHACL is een toevoeging aan RDF om UML constructen mogelijk te maken

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#4]
Een RDF-Ontologie is goed in het uitdrukken van semantiek en semantische relaties maar niet zo goed in het formuleren van constraints op die relaties. De constraints horen ook niet thuis in de open world assumption.

SHACL voegt de mogelijkheid toe om constraints eenvoudig te formuleren en toe te passen op een ontologie. De afstand tussen UML-XML en een ontologie is daarmee kleiner geworden.

Een modelleur moet zich wel afvragen of de constraints van belang zijn in de LD toepassing.

**Comment by architolk** [comment]
Dit is inmiddels opgenomen in de tekst van hoofdstuk 7.
