### ISSUE TITLE
Zijn GeoObject en Feature geen equivalent Classes?

### ISSUE THREAD

**Issue by joepvgenuchten** [Geonovum/NEN3610-Linkeddata#44]
in de NEN3610-Vocabulaire.ttl staat
nen3610:GeoObject a owl:Class;
	rdfs:label "Geo-object"@nl ;
	dcterms:subject concept:GeoObject;
	**rdfs:subClassOf geosparql:Feature ;**
	rdfs:seeAlso <http://schema.org/Place>

moet het vet gedrukte gedeelte niet "owl:equivalentClass geosparql:Feature ; " zijn (waarmee we zeggen dat het over de zelfde verzameling gaat?)

**Comment by pmaria** [comment]
Nee, want daarmee zeg je dat alle instanties van `geosparql:Feature` _in de wereld_ ook instanties van `nen3610:GeoObject` zijn en ik geloof niet dat dat het geval is. Ik geloof dat een nen3610:GeoObject wel degelijk een deelverzameling is.

**Comment by joepvgenuchten** [comment]
Maar is dat dan niet zo? Waar moet ik aan denken bij geosparql:Features die geen nen3610:GeoObject zijn?

**Comment by pmaria** [comment]
Goede vraag. Volgens mij alle niet Nederlandse sectorale-register-geo-objecten. NEN-3610 beschrijft bepaalde eigenschappen die een Nederlands sectorale-register-geo-object kan hebben welke niet gelden voor die geosparql:Feature instanties die geen Nederlands sectorale-register-geo-object zijn.
Maar, dit is mijn interpretatie.
De definitie van GeoObject in de NEN-3610 standaard is inderdaad vrij algemeen: 
> abstractie van een fenomeen in de werkelijkheid, dat direct of indirect is geassocieerd met een locatie relatief ten opzichte van de aarde

Ik ben benieuwd hoe anderen hier over denken.

**Comment by lvdbrink** [comment]
Dit deel van de spatial data on the web best practices gaat in op de definitie van Feature (oa): 

https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry 

Het zegt niets over NEN3610, maar helpt misschien wel in deze discussie. 

Mij lijkt subclass beter. We willen niet zeggen dat alle Features in de wereld ook NEN3610 GeoObjecten zijn... dat is de Nederlandse subset van Features zou ik zeggen.

**Comment by PalmJanssen** [comment]
De definitie van GeoObject is overgenomen van de term Geographic Feature uit de ISO 19125.

De definitie van Feature in iso19101 is: 

abstraction of real world phenomena


We hadden daar niet een specifieke NL context bij.
