### ISSUE TITLE
Hoofdstuk 6 issues

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/NEN3610-Linkeddata#45]
-	Par 6.1: Wat is de toegevoegde waarde van het uitdrukken van de verwijzingen in het linked data model? Wat kan je daarmee? Waarom geen links naar de standaarden? 
Ik vind dat we dit alleen moeten doen als het duidelijk toegevoegde waarde heeft. En die dan ook even uitleggen voor de lezer. 
- Par. 6.2: 
  - wbt de URI voor begrippen. Er is al https://definities.geostandaarden.nl/id/begrippenkader/nen3610
Laten we deze hergebruiken / updaten.
  - ttl publiceren is niet genoeg, moet in conceptenregister
- Par. 6.3: 
  - In de tabel met eigenschappen en klassen die we uit standaard vocabulaires gebruiken staat niet welke dingen we uit GeoSPARQL gebruiken.
  - Schema.org Place heeft een nauwere definitie dan Feature en Geo-Object. “Entities that have a somewhat fixed, _physical extension_.” Gebouw, Weg, Terrein, Water, Spoorbaan, Leiding, Kunstwerk, Inrichtingselement zijn wel kandidaat. De andere zijn virtuele objecten die geen fysieke aanwezigheid hebben. Zie ook https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry 
  - De URI voor de ontologie zou conform definities.geostandaarden uri strategie moeten zijn: https://definities.geostandaarden.nl/nen3610/def# 
  - Tekstuele definitie voor Identificatie ontbreekt.
  - Ik mis nog in de ontologie de VoidReasonValues en de eigenschappen voor formele historie, materiele levensduur en formele levensduur.

**Comment by pmaria** [comment]
> Tekstuele definitie voor Identificatie ontbreekt.

Ontbreekt ook voor alle klassen. We gebruiken overigens soms `rdfs:comment` en `skos:definition`. Mijn voorkeur ligt bij het gebruik van `rdfs:comment`  in de ontologie en alle skos properties bij de skos concepten.

> Ik mis nog in de ontologie de VoidReasonValues en de eigenschappen voor formele historie, materiele levensduur en formele levensduur.

**Over VoidReasonValues** moeten we het denk ik nog eens hebben. Ik zie geen manier om dat uit te drukken zonder een vorm van reïficatie. Zie ook https://geonovum.github.io/NEN3610-Linkeddata/#regels-attributen-voidable.
De codelijst zelf zouden wat mij betreft instanties van `skos:Concept` moeten zijn, omdat het om abstracte concepten gaat.

**Over formele historie en materiele- en formele levendsuur**
Ook deze eigenschappen kan ik alleen maar goed uitdrukken met een vorm van reïficatie. Dit kan in mijn optiek prima met PROV-O en foaf:Document.
Bovendien zou ik deze attributen (in een linked data kader) anders definiëren:

**attribuut met stereotype materieleHistorie**
attribuut voor historie van geldigheid van een set uitdrukkingen over een object in de werkelijkheid

**attribuut met stereotype formeleHistorie**
attribuut voor historie van geldigheid van de registratie van een set uitdrukkingen over een object in de werkelijkheid 

**attribuut met stereotype materieleLevensduur**
attribuut voor vastleggen van tijdsinterval van werkelijk voorkomen van uitdrukkingen over een object in de werkelijkheid

**attribuut met stereotype formeleLevensduur**
attribuut voor vastleggen van tijdsinterval van het in een registratie voorkomen van uitdrukkingen over een object in de werkelijkheid

_still with me?.._

**Comment by pmaria** [comment]
We zouden volgens mij ook rdfs:domain en rdfs:range kunnen opnemen bij de properties in het vocabulaire.

**Comment by lvdbrink** [comment]
Reïficatie... ik moet altijd weer even opzoeken wat dat betekent. Gevonden op [StackExchange](https://stackoverflow.com/questions/45610092/owl-reification-vs-rdf-reification): 

> RDF reification provides a way to talk about a statement in RDF."

Ik snap dan inderdaad dat je voor formele historie aan reïficatie denkt. Materiele levensduur gaat over wanneer iets in de werkelijkheid heeft bestaan (net als materiele historie, die we wel in de ontologie hebben opgenomen). Dus die zou ik met gewone triples uitdrukken. 

Wat betreft VoidReasonValues zou je ook aan reïficatie kunnen denken; maar wat we eigenlijk willen is onderscheid kunnen maken tussen dat iets in de werkelijkheid er niet is, of dat het er in de werkelijkheid wel kan zijn, maar de informatie om een of andere reden ontbreekt.  Het verschil tussen weten dat iets er niet is, en weten dat je niet weet of het er is ;-) 

Ik vond hiervan ook wel een mooi voorbeeld op [StackExchange](https://stackoverflow.com/questions/30877972/ontologies-owl-sparql-modelling-that-something-is-not-there-and-performance). 

De vraag is wel hoe hard wij het nodig hebben en wat we ervoor willen doen.

**Comment by pmaria** [comment]
Ja goed punt. Voor `geenWaarde` zou je een `NegativeObjectPropertyAssertion` kunnen toepassen, wat heel erg lijkt op `rdf:Statement` reification. 
Voor de anderen weet ik het nog niet.

**Comment by MarinusVonhof** [comment]
Ook kom je tegen "owl:minQualifiedCardinality = 0", waarmee je aangeeft dat relaties kunnen voorkomen, niet waterdicht natuurlijk.

**Comment by MarinusVonhof** [comment]
Toevoegen in sectie 6.2:
rdfs:isDefinedBy, rdfs:comment (a la Pano), skos:notation (voor coderingen)
Deze wel doen in sectie 6.2: ??
skos:broader, skos:related, dsterms:source, skos:inScheme, skos:Concept, skos:ConceptScheme, skos:scopeNote, dcterms:subject

**Comment by PalmJanssen** [comment]
Over de implementatie van het temporele model.

Ik zie de aanpassing van de definities van stereotypen. Kan dat nog moeilijk beoordelen.

Dit is de achtergrond van de huidige definities.

1) NEN 3610 heeft stereotypen waarmee de attributen herkenbaar gemaakt worden die gebruikt worden om het temporele model te implementeren.

2) In de huidige NEN 3610 hebben die attributen ook vaste namen. Zo wordt materiele historie altijd geimplementeerd met de twee attributen beginGeldigheid en eindGeldigheid. Deze twee attributen hebben in UML het stereotype `<<materieleHistorie>>`. Voor data implementatie en ik denk ook voor linked data heeft het stereotype `<<materieleHistorie>>` geen functie, behalve dat het de beginGeldigheid en eindGeldigheid groepeert.

3) Er wordt over gedacht bij de update van NEN 3610 de vaste benaming van deze attributen los te laten. De  naam voor beginGeldigheid zou dan vrij te kiezen zijn en bijvoorbeeld ook 'bouwjaar', of 'constructiedatum', of 'geboortedatum' of wat dan ook kunnen gaan heten met het stereotype `<<materieleHistorie>>`

4) Discussie over definitie attribuut beginGeldigheid. De huidige definitie is: Start van de periode waarop deze instantie van het object geldig is in de werkelijkheid. Er is een vraag waarom NEN 3610 het heeft over 'deze instantie van het object': het lijkt daarmee over de registratie te gaan. 

In NEN 3610 gaan we er van uit dat een instantie een representatie is van een object in de werkelijkheid. De zin 'start van de periode waarop deze instantie van het object geldig is in de werkelijkheid' heeft dan betrekking op de periode dat dat object daadwerkelijk voorkomt in de werkelijkheid en dus de periode waarin deze instantie een waarheidsgetrouwe representatie is. Dat kan trouwens een langere periode zijn dan dat de instantie zelf bestaat.

**Comment by architolk** [comment]
Inmiddels is er veel gewijzigd (waaronder de toevoeging van de temporele zaken). Maar ik overzie even niet of we hier alles mee geraakt hebben. Mogelijk goed om voor dit onderwerp nog een keertje bij elkaar te komen, of wellicht te combineren met een afspraak als we de reacties van de consultatieversie langslopen?

**Comment by PalmJanssen** [comment]
actie: check of het verwerkt is.

**Comment by lvdbrink** [comment]
> * Par 6.1: Wat is de toegevoegde waarde van het uitdrukken van de verwijzingen in het linked data model? Wat kan je daarmee? Waarom geen links naar de standaarden? Ik vind dat we dit alleen moeten doen als het duidelijk toegevoegde waarde heeft. En die dan ook even uitleggen voor de lezer.

Was niet gebeurd. Ik heb toegevoegd: "...zodat je ook kan verwijzen naar documenten die niet op het web staan."

> * Par. 6.2:
>  * wbt de URI voor begrippen. Er is al https://definities.geostandaarden.nl/id/begrippenkader/nen3610
>     Laten we deze hergebruiken / updaten.
>   * ttl publiceren is niet genoeg, moet in conceptenregister

**Is WEL in conceptenregister gepubliceerd, maar de bestaande URI is NIET hergebruikt.** Er is nu: https://definities.geostandaarden.nl/id/begrippenkader/nen3610 (oud) en ook http://definities.geostandaarden.nl/nen3610/id/conceptscheme/NEN3610 (nieuw)
Eén van de twee moet weg, anders verwarrend! 

> * Par. 6.3:
> * In de tabel met eigenschappen en klassen die we uit standaard vocabulaires gebruiken staat niet welke dingen we uit GeoSPARQL gebruiken.

Is gebeurd

>   * Schema.org Place heeft een nauwere definitie dan Feature en Geo-Object. “Entities that have a somewhat fixed, _physical extension_.” Gebouw, Weg, Terrein, Water, Spoorbaan, Leiding, Kunstwerk, Inrichtingselement zijn wel kandidaat. De andere zijn virtuele objecten die geen fysieke aanwezigheid hebben. Zie ook https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry

Is opgelost

>   * De URI voor de ontologie zou conform definities.geostandaarden uri strategie moeten zijn: https://definities.geostandaarden.nl/nen3610/def#

Is opgelost. URI op `def` eindigend is lastig in tools (rdf editors). Dan heet zo’n ontologie ‘def’. Is `def/nen3610` geworden.

>   * Tekstuele definitie voor Identificatie ontbreekt.

Is opgelost. 

>   * Ik mis nog in de ontologie de VoidReasonValues en de eigenschappen voor formele historie, materiele levensduur en formele levensduur.

Is opgelost.

**Comment by lvdbrink** [comment]
Publicatie issue is opgelost door @architolk. 3. De “nieuwe” begrippen zijn nu gemunt op de URI’s van de “oude” , en de “oude” verwijderd (zo behouden we feitelijk alle begrippen en het huidige begrippenkader, maar met de nieuwe teksten). Dit is redelijk eenvoudig, en zorgt er voor dat de oude URI’s nog kloppen (want hoewel de teksten mogelijk wat zijn aangepast, is de essentie niet anders geworden). 

Reden dat dit in het verleden niet is gebeurd was puur dat het nieuwe begrippenkader is gemaakt zonder te kijken naar het oude.
