### ISSUE TITLE
ConcreetObject toevoegen als class

### ISSUE THREAD

**Issue by pmaria** [Geonovum/NEN3610-Linkeddata#46]
In het NEN-3610-2011 document hoofdstuk 7.3 Semantisch Model wordt in 7.3.1 de term concreet object geintroduceerd:
> een groep van acht objecttypen van concrete objecten zie 7.3.2 t.m. 7.3.9;
Dit zijn objecten die fysiek (tastbaar, zichtbaar) begrensd in de werkelijkheid aanwezig zijn, bijvoorbeeld
een weg, gebouw of spoorbaan.

Dit is een interessant onderscheid om op Class niveau expliciet uit te drukken. Het biedt duidelijkheid over de aard van de beschreven objecten. Daarnaast biedt het extra ingangen voor analyses, en extra semantische koppelpunten voor andere data.

Voorstel:
Voeg `nen3610:ConcreetObject` toe als `rdfs:subClassOf nen3610:GeoObject`.
Maak deze klassen een `rdfs:subClassOf nen3610:ConcreetObject`

- `nen3610:Weg`
- `nen3610:Terrein`
- `nen3610:Water`
- `nen3610:Spoorbaan`
- `nen3610:Weg`
- `nen3610:Gebouw`
- `nen3610:Leiding`
- `nen3610:Kunstwerk`
- `nen3610:Inrichtingselement`

**Comment by MarinusVonhof** [comment]
De term Fysiek Object wordt algemeen gebruikt. Waarom maken we hier onderscheid, vast een (voor mij te) subtiel verschil? Beide types zijn te generiek om als subklasse van GeoObject te definiëren.

**Comment by architolk** [comment]
Dit lijkt in tegenspraak met het semantisch model in datzelfde hoofdstuk waarbij dit onderscheid niet meer terugkomt. Wel lijkt het me een goed idee, maar dan moeten we expliciet aangeven waarom we dit doen. @PalmJanssen : kun jij aangeven waarom in het oorspronkelijke model deze klasse niet is opgenomen?

**Comment by PalmJanssen** [comment]
In het NEN 3610 model is het niet als semantische klasse opgenomen omdat het geen functie had. Het had een functie in het begrip of definitie van de onderliggende klassen maar was geen operationele classificatie.
