### ISSUE TITLE
Structuur beschrijven met SHACL vs RDFS/OWL

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/NEN3610-Linkeddata#49]
In [hoofdstuk 5][1] staat bij de opsomming van onderdelen waaruit een linked data informatiemodel kan bestaan: 

> Een specificatie van de structuur die de gegevens in een linked dataset hebben, bijvoorbeeld eigenschappen die altijd aanwezig zijn, datatypen, enzovoort. Dit kun je uitdrukken met SHACL

Een opmerking die hierover is gemaakt is dat de structuur van de gegevens (soorten, unieke eigenschappen) ook (vooral?) met RDFS (rdfs:subClassOf) en met OWL-2 (owl:Restriction) te beschrijven is. (Marinus?)

Discussie hierover is nodig. Moeten we dit punt adresseren in de tekst? 

[1]: https://geonovum.github.io/NEN3610-Linkeddata/#intro

**Comment by NielsHoffmann** [comment]
tekst aangepast zodat het verschil tussen owl en shacl duidelijker wordt
