### ISSUE TITLE
Datatype en blank node

### ISSUE THREAD

**Issue by architolk** [Geonovum/NEN3610-Linkeddata#55]
In 7.3.4.1.3 wordt nu opgemerkt dat het niet mogelijk is om een Datatype om te zetten naar Linked Data, en dat hier een "normale" klasse van wordt gemaakt. Is dat wel waar? Je kunt hier een NodeShape van maken, zonder dat je er een klasse van maakt. Want een Datatype is geen Klasse in ontologische zin, maar feitelijk een "structuur". Ook is in dat geval geen sprake van een identificeerbaar object, maar van een complexe datastructuur, dwz: een blank node.

Voorstel: tekst en transformatie omvormen conform bovenstaande.

**Comment by pmaria** [comment]
Op zich is dit waar, alleen hadden we voor de algemene transformatieregels besloten dat de transformatie zowel in RDFS/OWL als in SHACL sense moest maken. Dus ook zonder SHACL zou ik met deze transformatie nog moeten kunnen werken met het resulterende model.

**Comment by architolk** [comment]
Check, maar als je voor SHACL kiest, kun je dus de klasse weglaten?

**Comment by architolk** [comment]
UITWERKING:
Opmerking bij de datatype transformatie dat als je SHACL erbij hebt, je er geen klasse van hoeft te maken, en bovendien dat je in de transformatie moet nadenken of je een blank node wilt introduceren, of een URI wilt verzinnen (en dan mogelijk een urn:uuid, omdat je er sowieso niet direct naartoe zou willen gaan...)

**Comment by architolk** [comment]
Verwerkt.
