### ISSUE TITLE
Enumeratie en Codelist vs skos:Concept

### ISSUE THREAD

**Issue by architolk** [Geonovum/NEN3610-Linkeddata#56]
In 7.3.4.1.6 en 7.3.4.1.7 wordt gesproken over enumeraties en codelijst. Hier wordt gekozen om geen implementatie naar sos:Concept te maken. Er valt nog te overwegen om dit wel te doen via een rdfs:subClassOf. Hiermee kun je dan identificeren dat sprake is van een enumeratie of codelist en niet zomaar een klasse. In de specifieke implementatie zou dat dan nog weggelaten kunnen worden.

**Comment by pmaria** [comment]
Ik zou niet standaard een `rdfs:subClassOf skos:Concept` willen toevoegen. Omdat je niet zeker kunt weten dat dat daadwerkelijk altijd klopt. Of dat het geval is zou ik handmatig willen bepalen.

**Comment by architolk** [comment]
Standaard niet nee, maar als optie, dwz om tot een juist model te komen?

**Comment by PalmJanssen** [comment]
Is meer een implementatie ding.
