### ISSUE TITLE
Transformatie volledige of niet?

### ISSUE THREAD

**Issue by architolk** [Geonovum/NEN3610-Linkeddata#57]
We hebben met elkaar nooit echt vastgesteld of we willen dat de transformatie van UML naar RDF volledig zou moeten zijn. Volledig in de zin dat de informatie die in het UML model zat ook in het getransformeerde model zit (wat te bewijzen is door weer terug te transformeren). Ik zou dit het liefst wel hebben: dan kun je het machinaal getransformeerde model gebruiken om "verder" te gaan, en hoef je niet meer terug naar het UML model op het moment dat je een meer specifiek LD model maakt. Dit lijkt ook in lijn met Figuur 6 in sectie 7.1

**Comment by JoepvanGenuchten** [comment]
In de scriptie van Ruben Haasjes beschrijft hij waarom de mogelijkheid om heen en terug te transformeren misschien wel bewijs is voor een volledige transformatie, maar niet voor een correcte (ik kan namelijk ook een onzin mapping maken en die volledig terug mappen) daarnaast laat zijn werk ook zien dat je bijna nooit het zelfde model terug krijgt omdat de mappings tussen UML en OWL _niet_ injectief en  _niet_ surjectief is (https://en.wikipedia.org/wiki/Injective_function)

**Comment by pmaria** [comment]
Dit zou inderdaad mooi zijn, maar dat vergt zoals we weten een mapping op metaniveau tussen UML en LD model. In onze huidige aanpak hebben we die niet. Dus lijkt me dit ook onmogelijk.

**Comment by architolk** [comment]
Het MIM heeft deze ambitie wel, maar mapt dan ook niet tussen UML en LD, maar tussen een metamodel en LD, en tussen een metamodel en UML. Vanuit LD kun je weer terug naar het metamodel, en daarmee ook weer naar UML. Wellicht hier naar verwijzen?

**Comment by PalmJanssen** [comment]
Verwijzen is goed idee. Mogelijk ook naar NEn 2660.

**Comment by architolk** [comment]
Uitwerking:
Zie #64

**Comment by architolk** [comment]
Verwerkt.
