### ISSUE TITLE
Commentaar Eric Oosterom, projectmanager GWSW

### ISSUE THREAD

**Issue by MarinusVonhof** [Geonovum/NEN3610-Linkeddata#60]
## Waar

Zie de beschrijving

## Samenvatting
Commentaar per e-mail van Eric Oosterom

## Beschrijving
Marinus,
Bij het snel doornemen zag ik twee kleine foutjes in de tekst van de LD-profiel-beschrijving.

•	Derde regel van 7.4.4.1 “geschreven de Gellish taal,” ontbreekt het woordje “in”
•	De eerste regel van paragraaf 8.2, daar lijkt “geen” te ontbreken tussen “Er is” en “applicatie”.

Twee andere punten die me opvielen:
•	In 9.3.1 staat “OroX is ontwikkeld in een periode dat de SHACL vocabulaire nog niet beschikbaar was. Dit verklaart het gebruik van OWL voor validatie.” Is dat het gehele verhaal? Ik dacht van jou begrepen te hebben dat OWL sowieso jouw voorkeur heeft, omdat dit universeler is dan SHACL. Of zou SHACL ook voor ons nu de logische keuze zijn?
•	Eigenlijk mis ik nog een paragraaf 9.4.5, waarin de laatste zin van 9.4.1 daadwerkelijk uitgewerkt wordt, namelijk: wat zijn de opvallende verschillen (volgens de werkgroep). Meer algemeen beloofd de inleiding op hoofdstuk 9 een vergelijking tussen modellen, datasets en LD stijlen, maar voor mij als niet-ingevoerde lezer komt dat in het hoofdstuk daarna maar deels uit de verf; er wordt wél gezegd dat het kan en deels hoe, maar ik zie het vervolgens niet gebeuren.

## Oplossingsrichting
In 9.3.1 de tekst wijzigen: Het OroX gebruikt de class expressions in OWL-2 om klassen zo expliciet mogelijk te beschrijving. Validatie van datasets vindt plaats met SPARQL-queries, tijdens de ontwikkeling van het OroX was de SHACL vocabulaire nog niet beschikbaar.

**Comment by PalmJanssen** [comment]
tekstvoorstel overgenomen en verwerkt
