### ISSUE TITLE
artikel over UML/GML naar OWL

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#62]
ter info.

Ik kwam dit artikel tegen:
https://www.researchgate.net/publication/264312253_Transforming_Between_UML_Conceptual_Models_and_OWL_2_Ontologies

Is dat bij ons bekend? Helpt het ons?

**Comment by pmaria** [comment]
Deze heb ik wel eens gelezen. Het lijdt aan dezelfde symptomen als veel van de andere transformatiebeschrijvingen. Het beschrijft namelijk een transformatie op basis van structuur, niet semantiek.
