### ISSUE TITLE
geodcat-ap en 19155:2003

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#63]
namens Paul van Genuchten
## Waar
hoofdstuk 2

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
“Voor een Linked Data model betekent dit dat voor metadata gebruik gemaakt moet worden van de [geodcat-ap] standaard, de Linked Data invulling voor de [iso-19115-1-2014] standaard voor het beschrijven van metadata over geometrische datasets.”

Belangrijk om te beseffen dat geodcat-ap gebaseerd is op iso19115:2003 (waar ook de nederlandse profielen op gebaseerd zijn). 
Ik weet daarnaast niet in hoeverre geonovum momenteel het gebruik van het GeoDCAT-AP profiel aanraadt, ander optie is namelijk de in afronding verkerende dcat2.0 standaard, waarin een aantal geo aspecten meegenomen zijn.

## Oplossingsrichting
Ik weet daarnaast niet in hoeverre geonovum momenteel het gebruik van het GeoDCAT-AP profiel aanraadt, ander optie is namelijk de in afronding verkerende dcat2.0 standaard, waarin een aantal geo aspecten meegenomen zijn.

**Comment by architolk** [comment]
Dit kan inmiddels inderdaad aangescherpt worden.

**Comment by architolk** [comment]
UITWERKING:
Van belang is dat in de originele standaard wordt verwezen naar het Nederlandse profiel op ISO19115, maar zonder versienummer, zowel niet in het profiel als in de ISO standaard. Dit volgen we voor LD, met daarbij de toevoeging dat inmiddels de DCAT 1.1 vrijwel definitief is, en dat ook het profiel zal worden geüpdatet, met linkjes erbij. Concreet wordt normatief dus dat je de betreffende standaard gebruikt, of zijn opvolgers.

**Comment by architolk** [comment]
Verwerkt.
