### ISSUE TITLE
transformatiedoel

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#64]
Namens Paul van Genuchten
## Waar
“Ons transformatiedoel is geslaagd als het RDF model dat ontstaat vanuit de transformatie van het UML model een model is van dezelfde UoD als die van het originele UML model.”

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
In deze zin ontbreekt een ambitie als “betekenisvol model” of “met minimaal informatieverlies”.
## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by architolk** [comment]
Tsja, het transformatiedoel zegt dat het dezelfde UoD beschrijft, niet of er informatieverlies daarbij op mag treden (wat namelijk het geval is, en andersom wordt informatie toegevoegd). Dat het een betekenismodel is, is impliciet, maar zou voor de duidelijkheid kunnen worden toegevoegd.

**Comment by PalmJanssen** [comment]
Ik heb wel de ambitie om dezelfde informatie-inhoud in het LD-model te krijgen. Het onderzoek gaat er om om te kijken of en hoe dat kan. De definitie van universe of discourse is dat het alles omvat wat voor de toepassing van belang is. Dat betekent dat er geen info verlies mag zijn.

**Comment by PalmJanssen** [comment]
zie #57

**Comment by architolk** [comment]
UITWERKING:
Toevoegen aan hoofdstuk 7: dat we geen roundtrip doen. Is niet het doel geweest, het gaat erom dat alle informatie wordt overgenomen die nodig is voor de link met het UoD. Daarbij kan informatie verloren gaan (zoals bepaalde structuren die wel relevant zijn voor UML, maar niet voor LD, bv de keuze wel/niet subklassen vs enumeraties van "typen"), en kan ook informatie missen. Ook verwijzen naar andere initiatieven, zoals https://github.com/Informatievlaanderen/OSLO-EA-to-RDF, die een UML hebben uitgebreid zodat je naar een juist OWL model kunt komen, of MIM, waarin we juist een model maken dat zowel UML als LD kan bedienen. Echte roundtrip komt dus in MIM, op basis van extensies.

**Comment by architolk** [comment]
Verwerkt.
