### ISSUE TITLE
UML RDF roundtrip wel of niet

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#65]
Namens Paul van Genuchten
## Waar
algemeen

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
Nou nog eentje dan, dank voor jullie werk in dit kader, er ligt een mooi stuk zo, theoretisch maar ook praktisch door de uitwerking van de cases.

De indruk die ik krijg is dat er in de transformatie een behoorlijke hoeveelheid informatie toegevoegd wordt aan de dataset, er worden links gelegd naar externe ontologien en objecten die in de oorspronkelijke dataset ontbraken. Dat brengt me op de vraag of de weg terug (van rdf naar uml) eigenlijk wel mogelijk, dan wel wenselijk is. De getransformeerde dataset zal zelf een eigen status krijgen, updates vanuit een achterliggend model zullen dit aspect moeten respecteren en bijvoorbeeld de initiële triples alleen corrigeren/aanvullen maar nooit in zijn geheel vervangen. 

Praktisch op de werkvloer speelt bijvoorbeeld de vraag; op een uml georiënteerde werkplek wordt data gegenereerd, deze wordt via transformatie ter beschikking gesteld aan een bredere doelgroep als linked data, door deze stap is het eenvoudiger geworden om inconsistenties in de data te detecteren en zullen er wijzigingsvoorstellen op de data komen. Om zo’n wijziging te verwerken zul je het wijzigingsvoorstel terug moeten vertalen uit de LD wereld naar de uml wereld.

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by pmaria** [comment]
Basically dezelfde vraag als #57

**Comment by architolk** [comment]
UITWERKING:
Zie #64

**Comment by architolk** [comment]
Verwerkt.
