### ISSUE TITLE
oplossing voor vergelijken van drie LD stijlen

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#67]
Door Lieke Verhelst
## Waar
9.3.1 Huidige stijlen in gebruik

## Samenvatting
De oplossing om met de 3 verschijningsvormen om te gaan is te simplistisch verwoord.

## Beschrijving

Er   wordt geconstateerd dat er met goede redenen 3  verschijningsvormen zijn van dezelfde   informatie. De oplossing om hier mee om te gaan ("Wel geldt dat de drie   Linked Data representaties makkelijker met elkaar zijn te vergelijken en aan   elkaar zijn te relateren (bijvoorbeeld met een owl:sameAs constructie),   aangezien in al deze gevallen sprake is van Linked Data") is te   simplistisch verwoord. Het gaat om een semantisch verschil, dit is niet   eenvoudig te koppelen doordat je hetzelfde data formaat (LD) gebruikt. Een   koppeling van twee resources met owl:sameAs is niet altijd semantisch   correct. Door dit zo op te schrijven wek je wellicht de suggestie dat je   alles wat op elkaar lijkt met owl:sameAs kan koppelen.

## Oplossingsrichting
Visualisatie van de huidige NEN 3610 concepten naast de vertaling naar linked data ontologie/informatiemodel. Eventueel opgesplitst in een aantal delen als het geheel te complex is om weer te geven.

**Comment by architolk** [comment]
De tekst mag wat aangepast worden, ook expliciet aangeven dat niet alleen owl:sameAs geldt. Daar moet je zorgvuldig in zijn. Oplossingsrichting lijkt me lastig, bovendien is er al een representatie gemaakt (in de bijlage). Mogelijk hier direct naar verwijzen?

**Comment by architolk** [comment]
UITWERKING:
Duidelijker maken dat je makkelijker kunt verbinden, omdat dit nu juist met LD kan, maar dat je semantisch nog steeds goed moet kijken of je het wel over hetzelfde hebt. En dat owl:sameAs dus slechts een oplossing is, als dit ook kan. Verwijzen naar het artikel  https://www.mdpi.com/2078-2489/10/10/310, waarin alternatieven worden aangedragen voor owl:sameAs, obv geosparql relaties.

**Comment by architolk** [comment]
Verwerkt.
