### ISSUE TITLE
verschil OO en Ontologie

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#68]
Door Arjan Santema
## Waar
hoofdstuk 5/6

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving

Het   document geeft een mooi en compleet beeld van de theorie en de praktijk in   Nederland voor het maken van een Linked Data profiel voor een NEN3610 model.   Het is veel meer dan alleen een standaard. Het geeft ook inzicht en   overzicht. Dit maakt het document ook praktisch bijzonder bruikbaar. Wij   herkennen de meeste punten die de vertegenwoordigers van het Kadaster in de   werkgroep hebben ingebracht, waarvoor onze complimenten.          Een punt waar wat meer aandacht aan kan worden gegeven is het fundamentele   verschil tussen het objectgerichte en ontologische gedachtengoed.

## Oplossingsrichting

Het   komt wel aan de orde in het document, maar het mag nog wel wat steviger   worden benoemd dat een object in het objectgericht UML iets anders is dan een   object in het ontologisch gerichte linked data denken. UML gaat uit van een   constructieperspectief op het UOD, in de linked data wereld gaat het alleen   om classificatie van dingen in een ontologie. Omdat we in de praktijk alleen   de beschrijving van informatie in UML gebruiken, is dit, zeker wanneer het   MIM wordt gebruikt als metamodel, geen issue meer.

**Comment by architolk** [comment]
De oplossingsrichting lijkt me een mooie toevoeging, die kan er prima bij lijkt me!

**Comment by lvdbrink** [comment]
Bij 5.3 een zin over UML toevoegen: daar ‘construeer’, maak, je klassen als een blauwdruk voor de instanties die je gaat uitwisselen.
