### ISSUE TITLE
relatie Core location Voc en W3C

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#69]
Door Arjan Santema
## Waar
[Geef aan over welke plek in het document de melding gaat. Bijvoorbeeld: 'Paragraaf x.x', 'pagina y'.]

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
Een ander punt is de relatie met het core location vocabulaire van de W3C.

## Oplossingsrichting

Wellicht   loopt die via geo-SPARQL, maar als dat zo is, is het goed om dat expliciet te   benoemen.

**Comment by architolk** [comment]
Is inderdaad een goed idee om het verband aan te geven, net als we met schema.org ook hebben gedaan.

**Comment by architolk** [comment]
UITWERKING:
De Core Location Vocabulary gaat over adressen en geometrieën. NEN 3610 gaat over geo-objecten, dat zijn dingen met een geometrie. De relatie loopt dus inderdaad van geosparql, in de zin dat een Geo-object een soort geosparql:Feature is.
In hoofdstuk 6 zal worden toegevoegd dat we de relatie naar de Core Location Vocabulary indirect gaat, en dat we in NEN 3610 geen klassen hebben die we rechtstreeks kunnen mappen op de Core Location Vocabulary (of andere klassen uit de e-Government Core Vocabularies)

**Comment by architolk** [comment]
Verwerkt.
