### ISSUE TITLE
Transformatie UML naar LD

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#70]
Door Mick Baggen
## Waar
Par. 5.5 en Hst 7

## Samenvatting
Transformatie UML naar LD

## Beschrijving

Er is   in dit profiel gekozen om een UML model te transformeren naar een LD profiel.   Gezien de historie van NEN 3610 is dit goed te begrijpen. Echter, een betere   aanpak was geweest om eerst het achterliggende conceptuele model achter de   NEN 3610 (in UML) te formuleren (wat heb je het nu echt over), en dan   vandaaruit zowel een UML model als een LD model te genereren. Dit voorkomt   dat je een hele (op zich interessante!) redenering moet gaan ophangen, zoals   in par 5.5, dat je in UML sloppy inheritance kunt toepassen, en in OWL niet.   Helaas is de praktijk anders: ook in OWL kom je behoorlijk veel sloppy   modellen tegen, waarbij de inheritance beroerd is vormgegeven. Als je dan   niets geeft om je reasoner, kom je daar gewoon mee weg.

## Oplossingsrichting

Zie   hiervoor: introduceer eerst een NEN 3610 als conceptueel model, en maak dan   een mapping naar zowel UML als naar LD. Een voorbeeld van deze aanpak is te   vinden in de NEN 2660.

**Comment by JoepvanGenuchten** [comment]
Is dit niet het gat dat MIM probeert te vullen? en zo ja, zou dat niet betekenen dat we NEN3610 eerst conform MIM moeten publiceren om vervolgens de vertalingen naar UML en OWL te maken?

**Comment by PalmJanssen** [comment]
Het NEN 3610 metamodel is beschreven in https://geonovum.github.io/NEN3610-Linkeddata/#transformatiebron Dat is de conceptuele basis om een UML- domeinmodel te interpreteren.

**Comment by architolk** [comment]
Mijn oplossingsrichting zou zijn: beschrijven dat we inderdaad voor NEN3610 dit hebben gedaan: we zijn uitgegaan van het conceptuele model, zoals in het NEN3610 document gespecificeerd, en hebben juist geen vertaling gedaan vanuit UML. Vervolgens hebben we een handreiking opgesteld voor de huidige praktijk waar veel UML modellen bestaan. Maar inderdaad: een betere aanpak zou zijn om vanuit een conceptueel model te werken, en dit dan te vertalen naar een implementatievorm, bv UML. Daarbij ligt het conceptuele model dicht aan tegen het LD model, maar ook daar zou je nog implementatiekeuzes kunnen maken. Wellicht moet dit nog ergens worden verduidelijkt?

**Comment by PalmJanssen** [comment]
zie #73 en #71

**Comment by architolk** [comment]
UITWERKING
Zie #71: Toevoegen van een sectie tussen 5.5 en 5.6

**Comment by architolk** [comment]
Verwerkt.
