### ISSUE TITLE
Referentiedata

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#71]
Door Mick Baggen
## Waar
Par. 5.6

## Samenvatting

Referentiedata

## Beschrijving

Het   voorbeeld over waterpartij en bunker is Par. 5.6 is zeer illustratief voor   een belangrijk modelleerprobleem. Je weet nl. nooit wanneer iemand anders nog   iets wil kunnen zeggen over een bepaald onderwerp, waar jij het al over gehad   hebt (een vorm van OWA). Daarom is de keuze om iets als een (enumerated)   literal te modelleren iets, en niet als een class, wat je in een conceptueel   model dus nooit doet. Pas bij de mapping/taalbinding (naar bv UML of LD)   bepaal je wat je met je class doet. En alleen als je zeker weet dat jouw   dataset niet gekoppeld gaat worden aan andere datasets (een soort CWA) mag je   dus een literal toepassen.

## Oplossingsrichting

Maak   scheiding tussen conceptueel modelleren (geen enumerations) en een   mapping/taalbinding waarin je een bewuste CWA beslissing neemt om iets als   een enumeration literal te modellen.

**Comment by pmaria** [comment]
IMO is er geen verschil tussen de modellering van een conceptueel model en goed LD model. Ik zie dan ook geen noodzaak om in de tekst dat onderscheid te maken. 

De opmerking over een CWA aanpak voor literals wanneer je zeker weet dat je dataset niet gekoppeld gaat worden begrijp ik niet in de context van referentiedata. Volgens mij willen we bij referentiedata juist koppelbare data, wat we bereiken door conceptueel goed te modelleren.

De enige CWA die ik mij voorstel in de context van referentiedata is het beperken/enumereren van de dingen/concepten die we in een bepaalde context willen uitwisselen. Daarbij wil je een aanpak kiezen waarbij je semantisch/talige model (RDFS/OWL) niet beperkt wordt, maar je in de uitwisseling van gegevens uitgedrukt in dat model mogelijk wel beperkingen (SHACL) wilt hebben. Daar zouden we hier nog wat over kunnen schrijven. In de transformaties komt dat overigens ook terug.

**Comment by architolk** [comment]
Het punt is wel terecht denk ik, maar niet van toepassing idd op een "goed" LD model: we onderkennen daar ook geen literals voor enumeraties. Mogelijk dat we dit wat kunnen verduidelijken?

**Comment by architolk** [comment]
UITWERKING:
In par 5.6 wordt toegevoegd dat we in LD geen literals doen voor enumeraties, maar juist URI's van resources. Daarnaast toevoegen van een paragraaf tussen 5.5 en 5.6 waarin we uitleggen wat de relatie is tussen de opdeling van modellen (van conceptueel tot implementatiemodel), en hoe dit in LD gaat. Zie ook #70

**Comment by architolk** [comment]
Verwerkt
