### ISSUE TITLE
relatie met NTA 8035

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#72]
## Waar
[Geef aan over welke plek in het document de melding gaat. Bijvoorbeeld: 'Paragraaf x.x', 'pagina y'.]

## Samenvatting

In   hoofdstuk 4 is geen verwijzing opgenomen naar de in ontwikkeling zijnde   standaarden NTA 8035, CEN Semantic Modeling and Linking Standard (SLMS) en   NEN 3610.

## Beschrijving

Dit is   begrijpelijk, omdat de genoemde standaarden nog in ontwikkeling zijn (net als   het NEN 2610 LD profiel). Paul Janssen (Geonovum) heeft een aantal   betrokkenen rondom de NTA/SLMS/NEN 2660 meegenomen in deze review. Het kan   echter leiden tot verschillende, niet-compatibele aanbeveling op LD gebied,   en dat lijkt niet handig.

## Oplossingsrichting

Borgen   structurele afstemming (niet op individueel persoon, maar op   organisatie-niveau) tussen beide trajecten. Benno Koehorst (RWS) kan hierbij   een coördinerende rol spelen.

**Comment by NielsHoffmann** [comment]
terechte opmerking.  verwijzing opgenomen in paragraaf 4.6
Het structureel oplossen van de afstemming tussen de verschillende trajecten is ook belangrijk, maar valt buiten de scope van dit document.
