### ISSUE TITLE
beschrijving NTA 8035 en NEN 2660

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#74]
Door Mick Baggen

## Waar

Par.   7.4.3 (NTA 8035)

## Samenvatting

Allereerst   excuses: ik had over het hoofd gezien dat in het LD profiel WEL aandacht was   besteed aan de in ontwikkeling zijnde standaard NTA 8035 (naast DSO, GWSW en   COINS). Mijn complimenten!

## Beschrijving

Er is   echter wel een kanttekening te maken: in par. 7.4.3.1 wordt het NTA metamodel   beschreven. In werkelijkheid bestaat dit uit een metamodel (op M2 niveau) en   een top level model (TLM, op M1 niveau). Zowel het NTA metamodel als het NTA   TLM zijn het resultaat van een specifieke mapping/taalbinding van het NEN   2660 conceptueel model (metamodel en top level model). In het NEN 2660 TLM en   onderliggende ontologieen is een rijker set aan relaties opgenomen, die in de   NTA niet terugkomen. Wil je de UML - LD mapping goed krijgen, moet je dus   toch eerst terug naar het conceptuele model (NEN 2660), om vandaaruit naar   UML en LD te mappen.

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by NielsHoffmann** [comment]
De tekst in 7.4.3 is wat verduidelijkt om recht te doen aan de relatie NTA-NEN2660.
In hoofdstuk 5 wordt al uitgebreid ingegaan op de verschillen tussen UML en LD, dat hoeft volgens mij in deze paragraaf niet terug te komen.Zolang het nieuwe conceptuele model van de NEN2660 nog niet gepubliceerd is, is het ook lastig daar naar te verwijzen.
