### ISSUE TITLE
definitie Vocabulaire

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/NEN3610-Linkeddata#75]
Door Hans Overbeek

## Waar
definitie vocabulaire

## Samenvatting
Wijkt   af van definitie in Wikipedia waarnaar wel verwezen wordt

## Beschrijving

Definitie   in NEN3610LD zegt “Een model van begrippen”. Wikipedia zegt: “a carefully   selected list of words and phrases”.

## Oplossingsrichting

Vocabulaire:   Een limitatieve lijst van begrippen die in een bepaald domein worden   gebruikt, bijvoorbeeld in een thesaurus of een ontologie. [en:] Controlled   vocabularies solve the problems of homographs, synonyms and polysemes by a   bijection between concepts and authorized terms. In short, controlled   vocabularies reduce ambiguity inherent in normal human languages where the   same concept can be given different names and ensure consistency.      Begrip: definitie van een term.  Een   term is de aanduiding van een begrip, de definitie is de uitleg van een   begrip.      Term + definitie = begrip

**Comment by JoepvanGenuchten** [comment]
De Engelstalige beschrijving heeft het ook over 'concepts' (concepten). Waarbij de referentie naar de semiotische driehoek wordt gemaakt. dit is m.i. een belangrijk onderwerp in de context van 'vocabulaires' en mis deze verwijzing nog in de Nederlandstalige beschrijving. Het is namelijk belangrijk om te erkennen dat termen in een vocabulaire slechts symbolen zijn die (zouden moeten) refereren aan concepten (mentale projecties). We gebruiken vocabulaires primair om er zo zeker mogelijk van te zijn dat we het 'over het zelfde hebben'.

**Comment by lvdbrink** [comment]
We passen de definitie van Vocabulaire aan en voegen Begrippenkader toe.

Vocabulaire: een verzameling van termen waarmee je je uitdrukt. 

Begrippenkader: Toevoegen aan lijst definities en definitie die nu bij 'vocabulaire' staat, behalve de laatste zin, die moet wel bij 'vocabulaire' staan. 

We moeten nog een keer door het document gaan om te zorgen dat we deze termen consequent toepassen. Deze termen worden in verschillende contexten verschillend gebruikt, we moeten ergens bovenin toelichten dat wij ze op deze manier gebruiken in dit document.
