### ISSUE TITLE
skos concept ConcreetObject bestaat niet als owl Class. is daar een reden voor?

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/NEN3610-Linkeddata#85]
In het begrippenkader bestaat er een skos concept ConcreetObject, waar concepten als Gebouw, Inrichtingselement, Terrein nauwere termen van zijn.
In het vocabulaire zijn de classes Terrein, Inrichtingselement e.d. direct subclasses van GeoObject.
Is er een reden voor dat er geen class ConcreetObject is?

**Comment by pmaria** [comment]
De term "concrete objecten" met bijbehorende definitie komt voor in de tekst van NEN 3610. Echter in het NEN3610 klassenmodel is deze niet opgenomen.
We hebben hier een tijd geleden over gediscussieerd en overwogen om ConcreetObject ook expliciet als klasse te introduceren. Echter, omdat dit gezien kon worden als een uitbreiding van NEN3610 is toen besloten om dit niet te doen.
Gezien het begrip wel voorkomt in NEN 3610 hebben we het wel als begrip opgenomen in het begrippenkader.

**Comment by architolk** [comment]
UITWERKING ISSUE:
In het begripsmodel (skos:editorialNote) komt de uitleg zoals Pano die ook al gaf. In de ontologie komt ook een opmerking dan ConcreetObject niet wordt gemaakt. Relatie met #70 : we hebben geen nieuwe model gemaakt in owl, maar het bestaande model overgenomen. Er is wel behoefte aan ConcreetObject, maar dat is aan de werkgroep die nu ziet op de vernieuwing van NEN3610

**Comment by architolk** [comment]
Verwerkt in https://github.com/Geonovum/NEN3610-Linkeddata/commit/a97c2144003ca092cafd6801b464b4473abbe33f
